<!DOCTYPE html>
<html lang="en">

<head>
	<title>BytescoutPDF source code example</title>
	
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>

	<!-- Downloadify (https://github.com/dcneiner/Downloadify#readme) script (Downloadify helps to download javascript-generated file even in old browsers which do not supports Data URI scheme for data streaming) -->
	<script type="text/javascript" src="downloadify.min.js"></script>
	<!-- helper file for Downloadify-->
	<script type="text/javascript" src="swfobject.js"></script>
	<!-- bytescoutpdf.js script containing BytescoutPDF class to generate PDF file -->
	<script type="text/javascript" src="bytescoutpdf1.15.150.js"></script>
	<!-- Helper script with CheckDataURISupport() function to determine if current browser supports Data URI scheme -->
	<script type="text/javascript" src="checkdatauri.js"></script>
    
    <script type="text/javascript">
	function CreatePDF(IsInternetExplorer8OrLower) {
	
	var pdf = new BytescoutPDF();

    // set document properties: Title, subject, keywords, author name and creator name
    pdf.propertiesSet("Sample document title", "Sample subject", "keyword1, keyword 2, keyword3", "Document Author Name", "Document Creator Name");

    // add new page
    pdf.pageAdd();
    
    pdf.textSetBoxPadding(3);

    // set text box
    pdf.textSetBox(50, 50, 500, 500);
    // and draw a rectangle around it
   // pdf.graphicsDrawRectangle(50, 50, 500, 500);

    // add aligned text:

    pdf.textSetAlign(BytescoutPDF.CENTER);
	pdf.fontSetSize(26);

    // set font style with parameters: bold, italic, underline
    pdf.fontSetStyle(true, false, false);
    pdf.textAddToBox('Piccadilly Biscuits Limited', true);
	if (!IsInternetExplorer8OrLower) // images and drawings from canvas are supported on IE version 9 and higher, other modern browsers should work fine
{
    // load image from local file
    pdf.imageLoadFromUrl('image1.jpg');
    // place this mage at given X, Y coordinates on the page
    pdf.imagePlace(170, 90);

} 
pdf.fontSetSize(24);

    // set font style with parameters: bold, italic, underline
    pdf.fontSetStyle(true, false, false);
    pdf.textAddToBox('HR Report', false);

	pdf.pageAdd();
	pdf.textSetAlign(BytescoutPDF.CENTER);
	pdf.fontSetStyle(true, false, true);
	pdf.textAddToBox("Content",true);
    // return BytescoutPDF object instance
    return pdf;
}

</script>
</head>

<body>


<!-- hidden images for pdf generation - BEGIN -->
<div id="pdfreportimages" style="display: none;">
    <img src="image1.jpg" id="pdfimage1"> 
    <img src="image2.jpg" id="pdfimage2"> 

</div>
<div id="getpdf">
<div>
</div>

			</div>
			</br>
			<script type="text/javascript">
				// 1st method implementation:
				// this function creates "a href" link to stream PDF via "Data URI scheme" feature supported in almost all modern browsers 	
				// uses div with "getpdf" id to place links
				// PDFContentBase64 parameter = pdf file content encoded with base64 encoding
				function CreatePDFDownloadLink(PDFContentBase64) 
				{
					// find "getpdf" DIV element that we use to show the link to view or download PDF 
					var pdfdiv = document.getElementById("getpdf");

					// check if we have Data URI enabled (using CheckDataURISupport() function from checkdatauri.js)
					if (CheckDataURISupport()) {
					
					    var warningNotice = "";
					    // added on May 5, 2015:
					    // check if we should show the message about Mac OS X Chrome/Chromium limitation:
					    // check if generated PDF size exceeds 128KB security limit used in Mac OS X version of Google Chrome
					    if (PDFContentBase64.length>128*1024)
					    {
					      
					    }
						

						// create the button code
						var buttonCode = '<button onclick=\"' + 'location.href = \'data:application\/pdf;base64,' + PDFContentBase64 + '\'";' + 
						'id=\"showPDFButton\" class=\"buttonClass\">Show PDF on Button click</button>';
                        
			                        // add the button code to the pdfdiv element existing code
                        			pdfdiv.innerHTML += buttonCode;

					}
					else {
						// Data URI is not supported so we should display the notice
						pdfdiv.innerHTML = "<h3><font color=\"red\">data URI scheme is not supported in current browser (seems like you are on IE8 or lower, you should use the 2nd method instead)</font><h3>";
					}
				};
			</script>
		
	   
			
			</br>
			<!-- downloadify element to show Download button made with Downloadify (works in almost all browsers including old ones) -->
			<div id="downloadify">
				You must have Flash 10 installed to download this file.


 <!-- important info about local server - end -->

			</div>
			</br>
			<script type="text/javascript">
				// [2] method implementation:
				// this function uses free "Downloadify" plugin that makes possible to download files generated by javascript
				// in almost all browsers (even in old versions)
				// this function places "download" button in div with "downloadify" id
				// PDFContentBase64 parameter = pdf file content encoded with base64 encoding 
				function CreatePDFDownloadifyButton(PDFContentBase64, WeHaveInternetExplorer8OrLower ) {

					// we use base64 encoding by default
					var dataTypeParam = 'base64';


						if (WeHaveInternetExplorer8OrLower )
						{
							dataTypeParam = 'string';					
						}

					Downloadify.create('downloadify', { // parameter to tell that we should place "Download" button in DIV element with "Downloadify" id
						filename: 'Sample.pdf', // filename to use when user want to save PDF file
						data: PDFContentBase64, // pass data encoded with base64
						onComplete: function () { alert('Sample.pdf has been saved!'); }, // message to show once saving local file has been completed
						onCancel: function () { alert('You have cancelled saving Sample.pdf'); }, // message to show if user canceled saving file (canceled Save File dialog)
						onError: function () { alert('Error occured while generating PDF file, please contact support@bytescout.com'); }, // message to show on error if something goes wrong
						transparent: false, // enable transparency for the button or not
						swf: 'downloadify.swf', // filename of SWF button (required for some old browsers)
						downloadImage: 'download.png', // image to use as a surface for download button
						width: 100, // width of the button
						height: 30, // height of the button
						append: false, // replace button to the current content of "Downloadify" div element or replace (we replace)
						dataType: dataTypeParam // set data type encoding
					});
				};                     
			</script>
		
	<!-- main part initializing and generating PDF - begin -->
	<!-- Source code sample with CreatePDF() function that uses bytescoutpdf.js API to generate PDF file and returns BytescoutPDF object instance -->
	<script type="text/javascript" src="createpdf.js"></script>
	<!-- main script to generate PDF and once PDF is generated then create links to download and/or view PDF -->
	<script type="text/javascript">


function getInternetExplorerVersion()
// Returns the version of Internet Explorer or a -1
// (indicating the use of another browser).
{
  var rv = -1; // Return value assumes failure.
  if (navigator.appName == 'Microsoft Internet Explorer')
  {
    var ua = navigator.userAgent;
    var re  = new RegExp("MSIE ([0-9]{1,}[\.0-9]{0,})");
    if (re.exec(ua) != null)
      rv = parseFloat( RegExp.$1 );
  }
  return rv;
}

	// checking if we are on IE, if IE then checking version
	ieversion = getInternetExplorerVersion(); // returns version for IE or -1 for non-IE browser

	var WeHaveInternetExplorer8OrLower = false;

					// if we are on IE 8 or earlier we can not use images and base64
					if (ieversion > -1)
					{ 
						if (ieversion < 9)
						{
							WeHaveInternetExplorer8OrLower = true;							
						}
					}

		if (WeHaveInternetExplorer8OrLower)
		{
			alert('You using on Internet Explorer 8 or lower so BytescoutPDF.js works in limited mode.\n\nThe limitation for IE8 (and lower):\nImages and Canvas drawings are not supported while generating PDF due to limitations of IE8 (and lower versions) and lack of HTML5 canvas\n\nMost modern desktop and mobile browsers should work fine.');
		}


    // define global variable "pdf" to store pdf generating object
    var pdf;
		
		
    // set pdf generation call to execute only after the whole window document is loaded		
    // REQUIRED WHEN YOU USE IMAGES WITH PDF FOR FIREFOX and IE: we use JQuery script to use $(window).onload() function event
    // so PDF generation runs only AFTER the whole page and all of its elements are loaded into the browser
    // if you use images in your PDF - see <!-- hidden images for pdf generation --> block above and put your images into this hidden block to preload them before pdf generation starts
	$(window).load(function(){

	    // calls CreatePDF() from createpdf.js to generate PDF file and return BytescoutPDF object instance		    	
        pdf = CreatePDF(WeHaveInternetExplorer8OrLower);		
		
		// now we set "onload" event for our PDF object into a custom function which will create links to view and download PDF once the generation is done
		// this is neccessary as PDF generation may take some time especially if you use images (so images should be downloaded and encoded)
		// so this function below will be called in "onload" event which is fired once PDF file generation has been completed
		pdf.onload(function() {

            // get generated PDF file in a form of encoded string
            var PDFContentBase64 = "";

	    // if we are on IE 8 or earlier we can not use base64. Browser variable is declared in getbrowserversion.js
 	    if (WeHaveInternetExplorer8OrLower )
	    {
		// we get the content as a string (non encoded as IE8 and Downloadify not working with base64)
		PDFContentBase64 = pdf.getText();
	    }
	    else{
	    // else we are using base64 encoded pdf
		PDFContentBase64 = pdf.getBase64Text();
	    }

            // now we create links to view or download PDF file generated (using method [1] - via "Data URI" supported in latest versions of most major browsers)
            CreatePDFDownloadLink(PDFContentBase64);
            // now we create "Download" button using "Downloadify" script which is aimed to provide a way to download generated file in almost all browsers (including old ones)
            CreatePDFDownloadifyButton(PDFContentBase64, WeHaveInternetExplorer8OrLower );
        });    
        
    }); // window.onload() end
  


	</script>
	<!-- main part initializing and generating PDF - end -->
	<!-- source code -->
</body>
</html>
